create database library;
use library;

CREATE TABLE ADMIN(
USER_ID VARCHAR(50) PRIMARY KEY,
NAME VARCHAR(50),
PASSWORD VARCHAR(50),
CONTACT VARCHAR(10)
);

INSERT INTO ADMIN VALUES ('satish@123','SATISH KUMAR','satish@1234','9447887856');

CREATE TABLE BOOKS(
BOOK_ID VARCHAR(50) PRIMARY KEY,
CATEGORY VARCHAR(50),
NAME VARCHAR(50),
AUTHOR VARCHAR(100),
COPIES INT
);

INSERT INTO BOOKS (BOOK_ID, CATEGORY, NAME, AUTHOR, COPIES)
VALUES
('B001', 'DATA STRUCTURE & ALGORITHMS', 'ALGORITHMS MADE EASY', 'NARSHIMA KARUMANCHI', 8),
('B002', 'JAVA', 'HEAD FIRST JAVA', 'KATHY SIERRA BERT BATES', 10),
('B003', 'INDIAN HISTORY', 'INDIA\'S ANCIENT PAST', 'R.S SHARMA', 18),
('B004', 'INDIAN POLITICS', 'THE GAME OF VOTES', 'FARHAT BASIR KHAN', 12),
('B005', 'NOVEL', 'THE GREAT GATSBY', 'F. SCOTT FITZGERALD', 8),
('B006', 'MYSQL', 'MURACH\'S MYSQL', 'JOEL MURACH', 5),
('B007', 'GEOGRAPHY', 'PRISONERS OF GEOGRAPHY', 'TIM MARSHALL', 5),
('B008', 'COMIC', 'THE SECRET LIFE OF DEBBIE G.', 'VIBHA BATRA', 15),
('B009', 'SCIENCE', 'COSMOS', 'CARL SAGAN', 20),
('B010', 'BIOLOGY', 'CONCEPTS OF BIOLOGY', 'REBECCA ROUSH', 14);

CREATE TABLE STAFFS (
    STAFF_ID VARCHAR(5) PRIMARY KEY,
    NAME VARCHAR(50),
    CONTACT VARCHAR(15)
);

INSERT INTO STAFFS (STAFF_ID, NAME, CONTACT)
VALUES
('S001', 'RAGHAV KUMAR', '786950432'),
('S002', 'PRAKASH KUMAR', '865427346'),
('S003', 'SHOBHIT TRIVEDI', '967321456'),
('S004', 'AJAY SINGH', '963431634'),
('S005', 'UMESH JHA', '886757439');

CREATE TABLE STUDENT_LOGIN (
    USER_ID VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(50),
    PASSWORD VARCHAR(50),
    STUDENT_ID VARCHAR(50),
    CONTACT VARCHAR(10)
);
CREATE TABLE STUDENTS( STUDENT_ID VARCHAR(50) PRIMARY KEY, BOOK_ID VARCHAR(50), BORROW_DATE VARCHAR(50), FOREIGN KEY(BOOK_ID) REFERENCES BOOKS(BOOK_ID));

INSERT INTO STUDENT_LOGIN (USER_ID, NAME, PASSWORD, STUDENT_ID, CONTACT) 
VALUES 
('user1', 'John Doe', 'password123', 'S1001', '9876543210'),
('user2', 'Jane Smith', 'mypassword', 'S1002', '9123456789'),
('user3', 'Alice Johnson', 'alicepass', 'S1003', '9988776655');

CREATE TABLE STUDENT_DETAILS(STUDENT_ID VARCHAR(20) PRIMARY KEY, NAME VARCHAR(50),YEAR INT(20),CLASS VARCHAR(20));

CREATE TABLE ISSUE_BOOK (
    ISSUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    STUDENT_ID VARCHAR(50),
    BOOK_ID VARCHAR(50),
    ISSUE_DATE VARCHAR(20),
    STATUS VARCHAR(50) DEFAULT 'pending',
    DUE_DATE VARCHAR(20),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_DETAILS(STUDENT_ID)
);
